// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIadrI9dZslFtzHKR_IVBECD-iKGSJGT8',
    appId: '1:855346823724:web:2d7c3c52f15d699afe8789',
    messagingSenderId: '855346823724',
    projectId: 'todo-92deb',
    authDomain: 'todo-92deb.firebaseapp.com',
    storageBucket: 'todo-92deb.firebasestorage.app',
    measurementId: 'G-08DVE4QJE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATvUqOvYOqwLcY0k1lfynFBbwkCw5xn0s',
    appId: '1:855346823724:android:274275d11e92ec16fe8789',
    messagingSenderId: '855346823724',
    projectId: 'todo-92deb',
    storageBucket: 'todo-92deb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASJMZZHl8iR2FfzYIZfaRIsWlXyyVXDno',
    appId: '1:855346823724:ios:a155337edcbfa97afe8789',
    messagingSenderId: '855346823724',
    projectId: 'todo-92deb',
    storageBucket: 'todo-92deb.firebasestorage.app',
    iosBundleId: 'com.example.taskmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASJMZZHl8iR2FfzYIZfaRIsWlXyyVXDno',
    appId: '1:855346823724:ios:a155337edcbfa97afe8789',
    messagingSenderId: '855346823724',
    projectId: 'todo-92deb',
    storageBucket: 'todo-92deb.firebasestorage.app',
    iosBundleId: 'com.example.taskmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCdH0PrKWcYcQp7QVvvkYHcs9-OqpQXt8',
    appId: '1:855346823724:web:dd06a1ebe4ed55bffe8789',
    messagingSenderId: '855346823724',
    projectId: 'todo-92deb',
    authDomain: 'todo-92deb.firebaseapp.com',
    storageBucket: 'todo-92deb.firebasestorage.app',
    measurementId: 'G-0WNKZ1QT6B',
  );
}
